/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSubjectsRouteImport } from './routes/app.subjects'
import { Route as AppResultsRouteImport } from './routes/app.results'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPremiumRouteImport } from './routes/app.premium'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as AppSubjectsIdRouteImport } from './routes/app.subjects.$id'
import { Route as AppStudyGuideChapterIdRouteImport } from './routes/app.study-guide.$chapterId'
import { Route as AppQuizChapterIdRouteImport } from './routes/app.quiz.$chapterId'
import { Route as AppLessonChapterIdRouteImport } from './routes/app.lesson.$chapterId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiumRoute = AppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsIdRoute = AppSubjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSubjectsRoute,
} as any)
const AppStudyGuideChapterIdRoute = AppStudyGuideChapterIdRouteImport.update({
  id: '/study-guide/$chapterId',
  path: '/study-guide/$chapterId',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizChapterIdRoute = AppQuizChapterIdRouteImport.update({
  id: '/quiz/$chapterId',
  path: '/quiz/$chapterId',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonChapterIdRoute = AppLessonChapterIdRouteImport.update({
  id: '/lesson/$chapterId',
  path: '/lesson/$chapterId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/results': typeof AppResultsRoute
  '/app/subjects': typeof AppSubjectsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/lesson/$chapterId': typeof AppLessonChapterIdRoute
  '/app/quiz/$chapterId': typeof AppQuizChapterIdRoute
  '/app/study-guide/$chapterId': typeof AppStudyGuideChapterIdRoute
  '/app/subjects/$id': typeof AppSubjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/results': typeof AppResultsRoute
  '/app/subjects': typeof AppSubjectsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/lesson/$chapterId': typeof AppLessonChapterIdRoute
  '/app/quiz/$chapterId': typeof AppQuizChapterIdRoute
  '/app/study-guide/$chapterId': typeof AppStudyGuideChapterIdRoute
  '/app/subjects/$id': typeof AppSubjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/results': typeof AppResultsRoute
  '/app/subjects': typeof AppSubjectsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/lesson/$chapterId': typeof AppLessonChapterIdRoute
  '/app/quiz/$chapterId': typeof AppQuizChapterIdRoute
  '/app/study-guide/$chapterId': typeof AppStudyGuideChapterIdRoute
  '/app/subjects/$id': typeof AppSubjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/app/achievements'
    | '/app/dashboard'
    | '/app/leaderboard'
    | '/app/premium'
    | '/app/profile'
    | '/app/results'
    | '/app/subjects'
    | '/app/'
    | '/app/lesson/$chapterId'
    | '/app/quiz/$chapterId'
    | '/app/study-guide/$chapterId'
    | '/app/subjects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/app/achievements'
    | '/app/dashboard'
    | '/app/leaderboard'
    | '/app/premium'
    | '/app/profile'
    | '/app/results'
    | '/app/subjects'
    | '/app'
    | '/app/lesson/$chapterId'
    | '/app/quiz/$chapterId'
    | '/app/study-guide/$chapterId'
    | '/app/subjects/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/app/achievements'
    | '/app/dashboard'
    | '/app/leaderboard'
    | '/app/premium'
    | '/app/profile'
    | '/app/results'
    | '/app/subjects'
    | '/app/'
    | '/app/lesson/$chapterId'
    | '/app/quiz/$chapterId'
    | '/app/study-guide/$chapterId'
    | '/app/subjects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subjects': {
      id: '/app/subjects'
      path: '/subjects'
      fullPath: '/app/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/results': {
      id: '/app/results'
      path: '/results'
      fullPath: '/app/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premium': {
      id: '/app/premium'
      path: '/premium'
      fullPath: '/app/premium'
      preLoaderRoute: typeof AppPremiumRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subjects/$id': {
      id: '/app/subjects/$id'
      path: '/$id'
      fullPath: '/app/subjects/$id'
      preLoaderRoute: typeof AppSubjectsIdRouteImport
      parentRoute: typeof AppSubjectsRoute
    }
    '/app/study-guide/$chapterId': {
      id: '/app/study-guide/$chapterId'
      path: '/study-guide/$chapterId'
      fullPath: '/app/study-guide/$chapterId'
      preLoaderRoute: typeof AppStudyGuideChapterIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quiz/$chapterId': {
      id: '/app/quiz/$chapterId'
      path: '/quiz/$chapterId'
      fullPath: '/app/quiz/$chapterId'
      preLoaderRoute: typeof AppQuizChapterIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lesson/$chapterId': {
      id: '/app/lesson/$chapterId'
      path: '/lesson/$chapterId'
      fullPath: '/app/lesson/$chapterId'
      preLoaderRoute: typeof AppLessonChapterIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSubjectsRouteChildren {
  AppSubjectsIdRoute: typeof AppSubjectsIdRoute
}

const AppSubjectsRouteChildren: AppSubjectsRouteChildren = {
  AppSubjectsIdRoute: AppSubjectsIdRoute,
}

const AppSubjectsRouteWithChildren = AppSubjectsRoute._addFileChildren(
  AppSubjectsRouteChildren,
)

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppProfileRoute: typeof AppProfileRoute
  AppResultsRoute: typeof AppResultsRoute
  AppSubjectsRoute: typeof AppSubjectsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppLessonChapterIdRoute: typeof AppLessonChapterIdRoute
  AppQuizChapterIdRoute: typeof AppQuizChapterIdRoute
  AppStudyGuideChapterIdRoute: typeof AppStudyGuideChapterIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppProfileRoute: AppProfileRoute,
  AppResultsRoute: AppResultsRoute,
  AppSubjectsRoute: AppSubjectsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppLessonChapterIdRoute: AppLessonChapterIdRoute,
  AppQuizChapterIdRoute: AppQuizChapterIdRoute,
  AppStudyGuideChapterIdRoute: AppStudyGuideChapterIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
